### ISSUE TITLE
new entity ogit/ITSM/ServiceRequest

### ISSUE THREAD

**Issue by conofre** [arago/OGIT#151]
Please create new entity ogit/ITSM/ServiceRequest with:

parent ogit/ITSM/Ticket

mandatory fields:
ogit/name
ogit/ITSM/solution
ogit/ITSM/resolutionCode

optional fields:
ogit/ITSM/actualStartAt
ogit/ITSM/actualFinishAt
ogit/ITSM/scheduledStartAt
ogit/ITSM/scheduledFinishAt

outgoing edges:

ogit/isRelatedTo => ogit/ITService/Order
ogit/isRelatedTo => arago/MARSNode
ogit/ITSM/requestedBy => ogit/Person

Many thanks.

**Comment by fotto** [comment]
ogit/solution 
might not really fit. "solution" is for incident stuff so for requests of kind " something is wrong. pls. find solution"
but ServiceRequest is more of type "pls. do something"

**Comment by conofre** [comment]
Canceling/postponing this request until further clarifications
