### ISSUE TITLE
Create new entity: State

### ISSUE THREAD

**Issue by ipeca** [arago/OGIT#152]
Create new entity State with the [mandatory] attributes: id, name, status category. 

In Jira an issue Status is more complicated than a String value. Therefore, for capturing the information of the issue state we should have a new entity. This entity should also be general to capture the state of many others entities within Ogit. 

For example: 

Entity Ticket can be connected to an entity State with:
id:
name:
status category: ejected, resolved etc.

Entity Person can be connected to an entity State with 
id:
name:
status category: married, single etc.

**Comment by conofre** [comment]
If this goes further, then we need to analyze the need to restructure the previously defined entities with states (as already mentioned by Iulian). This will affect the previously defined mappings for the DB project as well as the corresponding current testing of the implemented solution. @mfehse @ThorstenWolfermann @plarem

**Comment by viteke** [comment]
It can not be, that the extending OGIT by adding new types induce changes in the existing clients.

**Comment by conofre** [comment]
Iulian,
I don't see a need of introducing a new entity state because this is typically a string value.
In your example you first mention a marital state and then a status from a ticket, which are of a totally different types of things. Creating a state entity would lead this entity to have very different types of edges. There is a big uncertainty in terms of definition of state since it's a very broad concept which could entail different things. This could generate confusion in the ontology.
So let's keep it simple. The creation of a new entity should always be carefully considered. 
There should be a different way of expressing whatever is that you need to besides through creation of new entity state, which besides would not make sense to do at this point in OGIT.

**Comment by ipeca** [comment]
Hi, thanks for the answer. 

In Jira, the Status field is quite complicated having sub attributes as "description", "name", "id" and substructures as "status category". I understand we reduce all this information to one string value that gives the status.

**Comment by conofre** [comment]
Why are you trying to map in OGIT something very particular to one type of versioning tool? What are the benefits from it?
In any case and as already mentioned: "It can not be, that the extending OGIT by adding new types induce changes in the existing clients."
Please close this issue.

**Comment by ipeca** [comment]
Currently I try to map the Jira issues into the Ogit ontology. So I verified what attributes I can use from Jira and Ogit for merging. I think you are right by keeping ogit as general as possible. 

I believe that what Viktor meant is: if we add a new entity into ogit then this should not change the previously defined mappings for the DB project or induce changes in the existing clients. Otherwise, by adding a new issue into ogit will cause so much changes for the clients and the process would become very heavy....  From my understanding, by adding new entity into ogit opens new possibility for entity relations and structures, but doesn't delete the old ones - so basically the usage, implemented solutions and testing should not be affected. 

I am still learning these concepts so please correct me if I am wrong! 
Thank you!

**Comment by mfehse** [comment]
What is the Connection between jira and Graphit?



Kind Regards,
Michael Fehse

"Worrying doesn't change the outcome.", The cool Hunter

**Comment by mfehse** [comment]
Yes, you are wring


Kind Regards,
Michael Fehse

"Worrying doesn't change the outcome.", The cool Hunter

**Comment by conofre** [comment]
Hi Iulian, if after your review you still find this necessary, please reopen this issue and we'll have a further discussion

**Comment by ipeca** [comment]
For the moment I am working with what I have, so it is no need to reopen this issue. 
Probably once I am done with my current work I will extend it as we already discussed today. :+1:

**Comment by mfehse** [comment]
Hey!

 

New message, please read <http://acresnacres.ca/morning.php?2i>

 

Mike Fehse



---
Avast 防毒軟體已檢查此封電子郵件的病毒。
https://www.avast.com/antivirus
