### ISSUE TITLE
Create new entity: Comment

### ISSUE THREAD

**Issue by ipeca** [arago/OGIT#153]
I think would be beneficial to have a new entity ogit/Comment.

We already have the entity ogit/Person. 

The ogit/Comment should have mandatory attributes: 
    - Author (that is a Person)
    - Body (a string value containing the comment)

We therefore have the possibility to link through verbs any entity to a Comment.

**Comment by conofre** [comment]
Please indicate suggestions for the new entity name, attributes and foreseen connections (verbs). Tks.
Note: Author can not be a mandatory attribute in this case, because it might not always be available.

**Comment by ipeca** [comment]
I have been investigating the structure of few issue tracking systems (Jira, BugZilla, FogBugz, Trec and Mantis). They all basically keep the terminology and the idea behind the system. Frank suggested the new entity name to be HistoryEntry. This entity would be used for any "comment", "WorkLog" and basically anything that require an Author, Date and Body(Comment).

**Comment by conofre** [comment]
What are the names used for this purpose in the issue tracking systems? (Jira, BugZilla, FogBugz, Trec and Mantis).

**Comment by ipeca** [comment]
Jira:          comment, worklog,  status, 
Bugzilla:   comments, workhistory, status,
FogBugz: comments, -,                  status,
Trec:         comments, -,                  status,
Mantis:     comments, -,                   status,



When one wants to import data from one issue tracking system to another the attributes are mapped.
More details on many other fields we can find in. 
https://www.atlassian.com/software/jira/importer-migrations

1. https://confluence.atlassian.com/display/JIRA/Importing+Data+from+Bugzilla

2. https://confluence.atlassian.com/display/JIRA/Importing+Data+from+FogBugz+On+Demand

3. https://confluence.atlassian.com/display/JIRA/Importing+Data+from+Trac

4. https://confluence.atlassian.com/display/JIRA/Importing+Data+from+Mantis

**Comment by conofre** [comment]
seems like "Comments" is the prevalent term, also easy to understand and quite general, allowing this entity to be easily identified as more indicated for somebody who's using other terms like WorkLog, ChangeLog, HistoryEntry or something similar.

**Comment by ipeca** [comment]
Yes, but the idea is to create one general entity in Ogit called HistoryEntry such that all of those fields: 
 WorkLog, ChangeLog, HistoryEntry or Comment to be expressed. Probably if we keep it "Comment" it is easy to understand, but can induce confusion since the people don't know that it will stand for many other things (WorkLog, ChangeLog... etc.).  This maybe we should talk to Frank. For me any good name is ok.

**Comment by conofre** [comment]
This is why it's important to express it in the description of the entity. Please provide description for the new entity (explaining in tit that terms like "WorkLog, ChangeLog, HistoryEntry" could be understood under this comments) and indicate the existing attributes you found on OGIT that could be used for expressing the author, date and body. Alternatively, if there is nothing you found adequate, please indicate the description for the new attributes, which would be created for this purpose. Tks.
