### ISSUE TITLE
additional information in Entities needed

### ISSUE THREAD

**Issue by mglusiuk** [arago/OGIT#155]
For defining which attributes should be added to ogit/_content we need additional block in each entity which will contain a list of attributes which will be indexed for ngram search. Block could be optional and then nothing will be put to ogit/_content (default). GraphIt plugin will read from ontology on start which entities have defined attributes and do indexing as listener.

**Comment by thechriswalker** [comment]
For TabTab we define the fields we want to index in our application code, then if such a field is changed, we populate the `ogit/_content` field appropriately on update.

The question is should this be put into OGIT/GraphIT or remain "up-to-the-application" to decide what to index.

**Comment by mglusiuk** [comment]
It should be in OGIT because for example for entity type "arago/KnowledgeItem" we have different apps but still we need to index specified fields independend of application writing it. If ogit/_content will be set by application either it will be accepted or overwritten(need to be decided). If we have this defined in OGIT then we could simply recreate index from graph on demand or after sync without updating all data.

**Comment by thechriswalker** [comment]
That makes a lot of sense, our use case is slightly different as the entities are never read/written by any other application.

I believe we need to change the GraphIT API to disable writing to the `ogit/_content` field in that case, what do you think @p1tz?

**Comment by p1tz** [comment]
my proposed solution would be:

if we can add an attribute in the specification e.g. fields-to-index (never mind the name), the user could specify which fields to index in this field, and then forbid writing to it in general (make it an internal field).

**Comment by thechriswalker** [comment]
:+1:

**Comment by plarem** [comment]
Now you can index an attribute within the entity definition. see https://github.com/arago/OGIT/blob/master/SGO/format/Entity.yaml.tpl
Pls note that now also the attribute validation will be handled within the entity definition.

**Comment by thechriswalker** [comment]
Just to clarify, can someone confirm I have this correct? @p1tz @plarem 

 - All properties of a node (including free attributes) are indexed in the lucene index without analysing or tokenising.
 - Only properties corresponding to attributes in the entity definition with this new `indexed` parameter set to `true` will be added to the `ogit/_content` (as a single blob of all such attributes concatenated, space seperated) in the lucene index which has some analysis/tokenising done to it.
 - A side-effect of this is that you cannot add data from free attributes to the searchable `ogit/_content` field.

**Comment by p1tz** [comment]
yes, yes and yes.
