### ISSUE TITLE
New entity comment

### ISSUE THREAD

**Issue by conofre** [arago/OGIT#160]
Please create new entity: ogit/Comment
Description: Defines comments for a ticket, issue or another type of entity. Also known as WorkLog, ChangeLog or HistoryEntry.

Mandatory attribute: ogit/body
(Description of ogit/body: Contains the body of a message or comment)

Optional attributes: ogit/ITSM/lastUpdatedAt

Edge: ogit/comments From: ogit/Comment To: ogit/Comment
Edge: ogit/comments From: ogit/Comment To: ogit/Ticket
Edge: ogit/createdBy From: ogit/Comment To: ogit/Person

(Description of ogit/comments: Comments a ticket or a comment itself)

This issue is related to #159 and #153

**Comment by ipeca** [comment]
Looks good to me. When is Done I will include the Comment in my code. :+1:

**Comment by plarem** [comment]
done.
