### ISSUE TITLE
Ogit : Project Attribute required in ogit/itsm/Ticket. 

### ISSUE THREAD

**Issue by ipeca** [arago/OGIT#161]
![ogit_project](https://cloud.githubusercontent.com/assets/11459665/7228372/ba073560-e758-11e4-855d-64d5fe508de6.png)

I think in ogit/ITSM/Ticket we need an optional attribute ogit/Project.Here we should save the Project id for which the issue belongs to. As shown in the attachment, a company can have many projects. Each project has a number of issues. These issues are mapped to tickets in Graphit. For reverse mapping (From Graphit to the issue ticketing system) we we need to scan through all the issues to find the right project. Eg. "ticket 5" in Graphit has no information about the Project. Currently, to find that ticket 5 belongs to Project 3, we need to scan through all the issues. 

This attribute is also necessary since in many (if not all) issue-ticketing systems we have the element of "Product", "Project".

**Comment by conofre** [comment]
@ipeca optional attribute ogit/project will be added to entity ogit/ITSM/Ticket when executing the changes on the OGIT cleanup, till then please use it as free attribute (Note that Ticket already allows this - see last commit - #9e4a0826ff33ae4cc7c16e20f70f5ce55e4c619a

**Comment by conofre** [comment]
Hi Iulian, please close the ticket if no further action is needed, as the needed attribute was already defined in the new incoming changes and you can use it as free attribute meanwhile.
Tks.

**Comment by ipeca** [comment]
Closed.
