### ISSUE TITLE
ogit/Catalog/Catalog does not allow free attributes

### ISSUE THREAD

**Issue by sk-cool** [arago/OGIT#164]
We plan to use the ogit/Catalog/Catalog to map Software Catalog from ITOP. However it does not allow free attributes. We need free attributes to store ITOP specifc data.

Thanks,
-Satish

**Comment by conofre** [comment]
It now allows free attributes, change should be effective in <=1 hour
https://github.com/arago/OGIT/commit/9f44483332a5445ec9a0b92548a40aabc4aa1e33
