### ISSUE TITLE
New entity ogit/Automation/Set

### ISSUE THREAD

**Issue by conofre** [arago/OGIT#169]
New entity name: ogit/Set
New entity description: An entity to represent any type of set/grouping of other entities.

Optional attrs: ogit/name, ogit/description

Edge ogit/belongsTo:
from arago/MARSNode to ogit/Set

**Comment by plarem** [comment]
done

**Comment by viteke** [comment]
As a member of th OGIT board I put my veto on this entity type. It is too common and is a step backwards in the "more semantic" stuff in compare with the plain GraphIT and a completely free schema.

**Comment by conofre** [comment]
Agreed, it seems to me that the entity Set is too general. Peter could you please remove it from OGIT?

**Comment by plarem** [comment]
Set and corresponding connections are deleted.
