### ISSUE TITLE
frontend worksheet functionality

### ISSUE THREAD

**Issue by p1tz** [arago/OGIT#171]
Hi,

last year we developed some part of the ontology which is autopilot frontend specific.

I'll paste the ontology here. My questions

* could you please review and suggest better names :/
* could you please suggest where to put it

when I have your feedback, I will create a pull request with the updated things in order to minimize your work.

thank you :)

    - Entity:
        id:   http://www.purl.org/arago/av/Note
        name: Note
        description: |
          Defines A note of the AV-UI-Framework
        valid-from: 2014-09-15 00:00:00
        valid-until:
        creator: SP
        deleter:
        created:  2014-10-06
        modified: 2014-10-06
        admin-contact: ogit@arago.de
        tech-contact: ogit@arago.de
        scope: SGO
        parent: http://www.purl.org/arago/av/Note
        history:
          - id: 1
            date: 2014-10-06
            description: initial
            modified-by: SP

        attributes:
          mandatory:
            - http://www.purl.org/ogit/name
            - http://www.purl.org/ogit/content
          optional:
      
    - Entity:
        id:   http://www.purl.org/arago/av/Worksheet
        name: Worksheet
        description: |
          Defines A worksheet of the AV-UI-Framework
        valid-from: 2014-09-15 00:00:00
        valid-until:
        creator: SP
        deleter:
        created:  2014-10-06
        modified: 2014-10-06
        admin-contact: ogit@arago.de
        tech-contact: ogit@arago.de
        scope: SGO
        parent: http://www.purl.org/arago/av/Worksheet
        history:
          - id: 1
            date: 2014-10-06
            description: initial
            modified-by: SP

        attributes:
          mandatory:
            - http://www.purl.org/ogit/name
            - http://www.purl.org/ogit/content
            - http://www.purl.org/ogit/description
          optional:
            - http://www.purl.org/arago/av/deviceId
        
    - Entity:
        id:   http://www.purl.org/arago/av/Device
        name: Device
        description: |
          Defines A device of the AV-UI-Framework
        valid-from: 2014-09-15 00:00:00
        valid-until:
        creator: SP
        deleter:
        created:  2014-10-06
        modified: 2014-10-06
        admin-contact: ogit@arago.de
        tech-contact: ogit@arago.de
        scope: SGO
        parent: http://www.purl.org/arago/av/Device
        history:
          - id: 1
            date: 2014-10-06
            description: initial
            modified-by: SP

        attributes:
          mandatory:
            - http://www.purl.org/ogit/name
          optional:

    - Attribute:
        id: http://www.purl.org/arago/av/deviceId
        name: device Id
        description: |
          Contains A device of the AV-UI-Framework
        valid-from: 2014-09-05 00:00:00
        valid-until: 
        creator: SP
        deleter: 
        created:  2014-10-06
        modified: 2014-10-06
        admin-contact: arago AG
        tech-contact: arago AG
        validation-type:
        validation-parameter:
        history:
          - id: 1
            date: 2014-09-05
            description: initial
            modified-by: SP

**Comment by conofre** [comment]
Hi Stefan,
1-Could you please provide explanatory descriptions for each entity?
2-What does av stand for?
Tks.

**Comment by plarem** [comment]
av = autopilot visualizer

**Comment by conofre** [comment]
Hi Stefan, I looked through the changes and the existing descriptions, we could reuse some already existing entities.
The only description which I am missing: Worksheet

**Comment by p1tz** [comment]
hi,

could you point me to them please :)?

a worksheet is a configuration which defines a collection of views and their placement.
To generalize, i guess it would be something like an applicationconfiguration(?).

**Comment by conofre** [comment]
Changes:
Instead: http://www.purl.org/arago/av/Note
use: http://www.purl.org/ogit/Note
Description for the entity: Any type of note.

Attribute change: ogit/name optional, ogit/content - mandatory

Instead: http://www.purl.org/arago/av/Worksheet
use: http://www.purl.org/ogit/Configuration
Description for the entity: Any type of configuration.
Optional: ogit/name, ogit/content, ogit/description

Note: instead of having deviceId as an optional attribute in the entity, please define an edge to the entity ogit/Device (see related #172 )

**Comment by plarem** [comment]
done

**Comment by p1tz** [comment]
thank you very much, both of you! :+1:
