### ISSUE TITLE
Semantics and Generalisation

### ISSUE THREAD

**Issue by thechriswalker** [arago/OGIT#174]
I have been watching the progress of #169, as in the TabTab pull request #170 I used the `ogit/Set` entity. Now it has been removed.

I am struggling to understand the usage of the word `semantic` is relation to the graph entities/verbs/attributes. I thought it meant to be as specific as needed and as general as possible. Therefore an arbitrary collection of entities could be grouped with an `ogit/Set` node quite happily. It seems I was wrong, which may mean a lot of the pull request will need reworking.

Does the removal of `ogit/Set` mean that we should instead be requesting creation of entities like `ogit/NTO/SetOfThingA` or `ogit/NTO/ThingA/Set`? What is the preferred definition for group entities?

Thanks for the clarification, I am requesting a lot of changes, and want to understand what will work best in OGIT.

**Comment by plarem** [comment]
We have remove ogit/Set because it has no semantical meaning. ogit/Set could contain any types and combination of entities. But these is not the sense of the ontology. 
e.g. a group of MARSNodes is a MARSModel (not a ogit/Set connected to MARSNodes)
or  a group of Paragraphs is a Statute (not in OGIT yet :-) ) and so on.

Don't use ogit/NTO/ThingA/Set. Use ogit/NTO/SemanticNameOfAnGroup.
I hope it helps you.
And sorry for the confusion of ogit/Set.

**Comment by thechriswalker** [comment]
OK, that's cool, your response is super helpful! I will probably need to change my pull request (but that's a good thing).

**Comment by conofre** [comment]
Hi Chris,
I am reviewing the pull request and was also commenting the same thing because of entity Collection, I will provide my feedback shortly at the pull request with some suggested changes/questions

**Comment by thechriswalker** [comment]
@conofre it might be easier for you to review the "files changed" in a pull request, rather than the commits one by one. Later commits change changes in earlier commits. Github allows you to view the combined diff in one go. I only say this, because `ogit/Collection` is not in the final code of the pull request, but you mention it here. A later commit removes all references to `ogit/Collection` changing it to `ogit/Set`. This will be changed soon by another commit where I use more semantically correct entities for grouping objects.
