### ISSUE TITLE
Links to purl not working

### ISSUE THREAD

**Issue by conofre** [arago/OGIT#178]
Hi, 

I noticed some links to purl might be missing, e.g. requesting the page:
http://www.purl.org/ogit/Asset 

returns: "Purl: /ogit/Asset has been tombstoned and cannot be resolved."

other links are not working properly:
http://www.purl.org/ogit/Person

returns: "The proxy server could not handle the request GET /doxygen-graphit/group__httpwwwpurlorgogitPerson.html.
Reason: Error during SSL Handshake with remote server"

Some might to be missing at all from purl:
http://www.purl.org/ogit/_version
http://www.purl.org/ogit/corresponds

returns: "HTTP 404 Not Found."

**Comment by plarem** [comment]
- manual purl registration no langer needed
done
