### ISSUE TITLE
SLA Entity- New edges and attributes

### ISSUE THREAD

**Issue by Ay-men** [arago/OGIT#179]
Please add the following new edges between SLA entity and Incident / ChangeRequest/ Problem:

ogit/ServiceManagement/Incident => ogit/ complies ogit/ServiceManagement/SLA
ogit/ServiceManagement/ChangeRequest => ogit/complies ogit/ServiceManagement/SLA
ogit/ServiceManagement/Problem =>  ogit/complies ogit/ServiceManagement/SLA

For the external tools that the connectors will deal with i suggest adding the following attributes for the SLA entity as optional attributes:

- startTime: Creation time of the SLA
- actualTimeLeft: Time remaining until SLA breach
- actualTimeElapsed: time between start time and now (minus pause duration).
- plannedEndTime: When the SLA will become breached
- stage: Stage values which are defined for task SLA records (In progress, Breached, Achieved, Cancelled, Completed, Paused)

**Comment by conofre** [comment]
@Ay-men 
In order to have all SLA related changes in one issue, please add missing optional attributes for entity SLA and their descriptions in case it's a new attribute.
(This issue should be resolved as an exercise Monday afternoon.)

**Comment by Ay-men** [comment]
Alles klar !

**Comment by Ay-men** [comment]
Done!

**Comment by plarem** [comment]
Hi Aymen,
The new attribute files are fine. But one error was there. The files need the .yaml extension. :-) I have add it, so now all the stuff have to work.

**Comment by Ay-men** [comment]
Hi Peter,

Ah, yes.
I have seen it, when i created the entity. I thought the file format should be added automatically.
But thank you for the notification.

Best regards / Mit freundlichen Grüßen
Aymen Ayoub

--

Aymen Ayoub
Automation Expert

arago GmbH

Eschersheimer Landstraße 526 - 532
60433 Frankfurt am Main

E-Mail: aayoub@arago.de<mailto:aayoub@arago.de> - www: http://autopilot.co<http://autopilot.co/> - http://arago.co<http://arago.co/>
Tel: +49-0170-5461481
Fax: +49-69-40568-111
--
Bankverbindung: Frankfurter Sparkasse, IBAN: DE08 5005 0201 0000 0793 43, BIC: HELADEF1822
Geschäftsführer: Boos, Hans-Christian - Registergericht: Amtsgericht Frankfurt am Main
Geschäftsanschrift: Eschersheimer Landstraße 526, 60433 Frankfurt am Main - HRB 100909
Ust.Idnr. DE 178572359 - Steuernummer 2603 003 228 43435

Von: plarem <notifications@github.com<mailto:notifications@github.com>>
Antworten an: arago/OGIT <reply@reply.github.com<mailto:reply@reply.github.com>>
Datum: Dienstag, 9. Juni 2015 09:28
An: arago/OGIT <OGIT@noreply.github.com<mailto:OGIT@noreply.github.com>>
Cc: Aymen Ayoub <aayoub@arago.de<mailto:aayoub@arago.de>>
Betreff: Re: [OGIT] SLA Entity- New edges and attributes (#179)


Hi Aymen,
The new attribute files are fine. But one error was there. The files need the .yaml extension. :-) I have add it, so now all the stuff have to work.

-
