### ISSUE TITLE
GraphIT problems when changing mandatory attrs to optional in new version

### ISSUE THREAD

**Issue by conofre** [arago/OGIT#181]
Hi Stefan,

When loading in GraphIT:

ontology_1
with entity_1
with attribute_1 = mandatory

and then later load:

ontology_2
with entity_1
with attribute_1 = optional

GraphIT does not recognize attribute_1 = optional, but still treats it as = mandatory
Because of this behavior, we can not properly work with OGIT ontology in the context of ConnectIT.
Could you please help?

@p-a-x @Ay-men @PPelchmann

**Comment by fotto** [comment]
this has nothing to do with the ontology itself . it is an implementation issue. Pls. report as ticket for GraphIT Server.

**Comment by p-a-x** [comment]
@p1tz explained that the ontology management is already a defined item on the list for future development but with an undefined implementation date.

The only temporary solution is the deletion of the ontology via admin console and a reload of the new one.

**Comment by conofre** [comment]
thank you @fotto , this happens as a result from the current setting in GraphIT which loads several ontologies at the same time
