### ISSUE TITLE
Connecting the inc process (SDF related changes)

### ISSUE THREAD

**Issue by conofre** [arago/OGIT#182]
attr ogit/connectorID
entity ogit/Software/Connector with optional attrs ogit/connectorID, ogit/name
edge ogit/Software/Connector -> ogit/opens Incident

entity ogit/ServiceManagement/Incident  - add attr ogit/category

del attr ogit/ServiceManagement/externalTicketSource and from Ticket because this kind of info will be mapped through an edge

attr ogit/sourceId
ent ogit/Person - optional attr ogit/sourceId
edge ogit/Software/Connector -> ogit/correspond

ogit/ConfigurationItem - new entity
ogit/ConfigurationItem-> ogit/corresponds ogit/Automation/MARSNode

**Comment by conofre** [comment]
Additionally:
edge ogit/ServiceManagement/Incident => ogit/affects (ogit/ServiceManagement/service)
edge ogit/ServiceManagement/Incident-> locatedIn ogit/Location

**Comment by Ay-men** [comment]
Done!
