### ISSUE TITLE
Proposed changes related to ChangeRequest & Incident

### ISSUE THREAD

**Issue by mderichs** [arago/OGIT#183]
ent ogit/ServiceManagement/ChangeRequest new opt attr ogit/ServiceManagement/sourceStatus
new attr ogit/justification  
ent ogit/ServiceManagement/ChangeRequest new opt attr ogit/justification
ent ogit/ServiceManagement/ChangeRequest new opt attr ogit/category
ent ogit/ServiceManagement/ChangeRequest new opt attr ogit/ServiceManagement/solution
ent ogit/ServiceManagement/ChangeRequest new opt attr ogit/ServiceManagement/resolutionCode
ent ogit/ServiceManagement/ChangeRequest new opt attr ogit/reportedAt
new attr ogit/reviewedAt
ent ogit/ServiceManagement/ChangeRequest new opt attr ogit/reviewedAt
ent ogit/ServiceManagement/ChangeRequest rename attr ogit/startAt to ogit/startedAt
ent ogit/ServiceManagement/ChangeRequest rename attr ogit/finishAt to ogit/finishedAt
new attr ogit/assignedGroup  
ent ogit/ServiceManagement/ChangeRequest new opt attr ogit/assignedGroup
new attr ogit/ServiceManagement/customer  
ent ogit/ServiceManagement/ChangeRequest new opt attr ogit/ServiceManagement/customer
new edge ogit/affects (ogit/ServiceManagement/ChangeRequest) => (ogit/ServiceManagement/Service)
new edge ogit/affects (ogit/ServiceManagement/ChangeRequest) => (ogit/ConfigurationItem)
new edge ogit/locatedIn (ogit/ServiceManagement/ChangeRequest) => (ogit/Location)

ent ogit/Software/Connector rename ogit/connectorID to ogit/connectorId
ent ogit/ServiceManagement/Incident new opt attr ogit/assignedGroup
ent ogit/ServiceManagement/Incident new opt attr ogit/ServiceManagement/customer
new attr ogit/ServiceManagement/task
ent ogit/ServiceManagement/Incident new opt attr ogit/ServiceManagement/task
ent ogit/ServiceManagement/Incident new opt attr ogit/ServiceManagement/reportedSource

**Comment by conofre** [comment]
additionally:
ent ogit/ServiceManagement/Incident new opt attr ogit/ServiceManagement/reportedSource

**Comment by Ay-men** [comment]
Done.
