### ISSUE TITLE
new entities in ogit/Automation needed

### ISSUE THREAD

**Issue by plarem** [arago/OGIT#184]
we need following things:
- new entity ogit/Automation/DynamicEngineData
- new connection of "ogit/contains" from: ogit/Automation/DynamicEngineData, to: ogit/Automation/DynamicEngineData
- new connection from ogit/Automation/MARSNode to ogit/Automation/DynamicEngineData, Verb should be like the old "hasMARSData", now it can be "ogit/availableIn", "ogit/relates"???
- new connection from ogit/Automation/AutomationIssue to ogit/Automation/DynamicEngineData, Verb could be "ogit/describes", "ogit/availableIn", "ogit/relates"? Pls take notice of the direction of the verbs

**Comment by mglusiuk** [comment]
Please review and merge https://github.com/arago/OGIT/pull/185

**Comment by plarem** [comment]
done
