### ISSUE TITLE
Question about verb "ogit/employs"

### ISSUE THREAD

**Issue by plarem** [arago/OGIT#189]
Within the clean-up ogit project the former verb "ogit/isMemberOf" was replaced by "ogit/employs".
Now there is only one connection "ogit/Organization => ogit/employs => ogit/Person". 

We need something Person is member of organization (group, team, department, yammer-group...).
Is the verb "ogit/employs" the right one for this case??? Or do we need another connection, e.g. ogit/belongs? Or is it ok to put a connection with other direction "ogit/Organization <= ogit/employs <= ogit/Person"?

What is your opinion?

**Comment by conofre** [comment]
Hi Peter,
Yes, belongs could be a good alternative/addition in case of need.
Person employs Organization sounds at least to me a bit confusing semantically.
Other alternatives are also welcome, if you have further ideas please share.

**Comment by fotto** [comment]
in many cases the only information about a person is membership to one organization.
Using "employs" in this case imposes some semantic meaning on the relationship which is not really there.

Hence we need some replacement for "isMemberOf". we can choose among several possibiities:

Person->belongs(to)-> Organization 
Organzation->has->Person
Organization>contains->Person

**Comment by conofre** [comment]
belongs seems to be the best suggestion till now

**Comment by plarem** [comment]
I add new connection ogit/Person -> ogit/belongs -> ogit/Organization
