### ISSUE TITLE
Incident related changes

### ISSUE THREAD

**Issue by conofre** [arago/OGIT#192]
Please:

add missing optional attr ogit/ServiceManagement/resolvedInTime for entity ogit/ServiceManagement/SLA

remove edge ogit/Software/Connector => ogit/opens ogit/ServiceManagement/Incident

add edges:
ogit/Software/Connector => ogit/creates ogit/ServiceManagement/Incident
ogit/Software/Connector => ogit/creates ogit/ServiceManagement/ChangeRequest

**Comment by plarem** [comment]
Normally deleting something will affect an increase of first position of the version. If you are sure nobody else use this connection delete it without increasing first position of the version.

**Comment by conofre** [comment]
it was only created for ConnectIT purpose very recently, so yes absolutely sure! :-)

**Comment by PPelchmann** [comment]
done
