### ISSUE TITLE
Is there any scope for a "rejects/opposes/invalidates" edge

### ISSUE THREAD

**Issue by brendanmoore** [arago/OGIT#198]
I don't see any verbs in the SGO which have obvious opposites, we have `endorses` but no `opposes`. Is there any reason why there are not any?

**Comment by plarem** [comment]
Because no such cases are used yet?! If you need an "opposes" let us know.

**Comment by brendanmoore** [comment]
Okay cool, I thought that may have been a design decision. I am working on something that will have a good use case for `accepts/rejects` I will update when I have a spec.

**Comment by brendanmoore** [comment]
closed via #200
