### ISSUE TITLE
What is `ogit/id` used for in Comment?

### ISSUE THREAD

**Issue by brendanmoore** [arago/OGIT#199]
What is expected to go in this field? and why is it different to `ogit/_id`? And why is it mandatory? 

https://github.com/arago/OGIT/blob/d1d932fda045cff5ac1355e95f7a656cf1a4e43a/SGO/sgo/entities/Comment.yaml#L18

**Comment by plarem** [comment]
First of all, all attributes beginning with "_" e.g. ogit/_id are internal attributes and are only used by graphit itself. Actually these attributes have to remove from ogit and switch to the documentation of graphit. 
ogit/_id is the internal id (of the comment vertex) within the graph, ogit/id should be here the id of the ticket where the comment is linked to. But the connector team can hopefully say more about and why this is mandatory. :-)

**Comment by Ay-men** [comment]
We need a mandatory attribute in each Comment entity to be able to distinguish between comments which belongs to an incident.

**Comment by brendanmoore** [comment]
What if a Comment is not for an incident? Should it be mandatory?

**Comment by brendanmoore** [comment]
TabTab uses `ogit/Comment` and they are not for incidents.

**Comment by Ay-men** [comment]
So it has not to be a mandatory field in Ogit, if it disturbs TabTab, Its enough for us to check this is the SDF format. So i will update this to be as an optional attribute..

**Comment by brendanmoore** [comment]
:+1: .
