### ISSUE TITLE
Entity documentation incorrect

### ISSUE THREAD

**Issue by thechriswalker** [arago/OGIT#217]
Definition here:
https://github.com/arago/OGIT/wiki/OGIT-ontology-details#entity-definitions

does not match implementation, here:
https://github.com/arago/OGIT/blob/master/SGO/sgo/entities/Timeseries.yaml#L23

I assume the implementation is correct and the documentation needs updating.

**Comment by plarem** [comment]
That's right. The implementation is correct and the doc will be updated.
