### ISSUE TITLE
define new attributes for engine vertices

### ISSUE THREAD

**Issue by mglusiuk** [arago/OGIT#219]
Please add 2 new optional attributes for each of this Entities:
MARSNode, AutomationIssue, KnowledgeItem

I need smth like this(maybe we have smth already?): 

"deployed" = deployed to engine(boolean)
"deployStatus" = if not deployed will contain message why

**Comment by plarem** [comment]
new attributes ogit/Automation/isDeployed and ogit/Automation/deplayStatus are created
