### ISSUE TITLE
Attributes for ogit/Knowledge/AcquisitionSession

### ISSUE THREAD

**Issue by vteremasov** [arago/OGIT#478]
Add several optional attributes for `ogit/Knowledge/AcquisitionSession` and make it indexed to make case insensitive search.

- `ogit/title` - indexed string
- `ogit/description` - indexed string
- `ogit/archived` - not indexed bool

**Comment by miraage** [comment]
cc @bpneal

**Comment by bpneal** [comment]
@miraage have these changes been done? or are you needing them to be done for you?

**Comment by miraage** [comment]
@bpneal we need those fields for search in ATQ

**Comment by vteremasov** [comment]
https://github.com/arago/OGIT/pull/477 solves it
